print("hola mundo")
print("Ingrese su N° de vendedor:")
número_de_vendedor=input()
print("Ingrese la cantidad de ventas realizadas:")
cantidad_de_ventas=int(input())
print("Ingrese el valor total de sus ventas")
valor_de_ventas=int(input())
print("N° de vendedor:", número_de_vendedor)
print("Su salario correspondiente es: ", 800+cantidad_de_ventas*50+valor_de_ventas/20)
